terminate called after throwing an instance of 'std::runtime_error'
  what():  could not open mt-matmul.elf (did you misspell it? If VCS, did you forget +permissive/+permissive-off?)
